package proyectoprimerparcial_zapata.verduzco;

/**
 * @author M. Zapata & M. Verduzco
 * Todos los botones tienen la misma estructuta:
 *      jTextField1.setText(cad+="#");
 * de tal manera que a la cadena se le agrega el simbolo correspondiente al botón y luego se imprime en el TextField
 * 
 * los casos especiales son:
 * 1.- el AllClear en el que la cadena se "borra" al igualara a una cadena vacía "";
 * 2.- el Igual, en el que la cadena se iguala a la Función Principal ejecutada con la cadena cómo atributo.
 * 
 */

public class Calculadora extends javax.swing.JFrame {
    private String cad;/**

    /**
     * Creates new form Calculadora
     */
    
    public Calculadora() {
        this.cad = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButtonCero = new javax.swing.JButton();
        jButtonPunto = new javax.swing.JButton();
        jButtonAbierto = new javax.swing.JButton();
        jButtonCerrado = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonUno = new javax.swing.JButton();
        jButtonDos = new javax.swing.JButton();
        jButtonTres = new javax.swing.JButton();
        jButtonMas = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jButtonCuatro = new javax.swing.JButton();
        jButtonCinco = new javax.swing.JButton();
        jButtonSeis = new javax.swing.JButton();
        jButtonSiete = new javax.swing.JButton();
        jButtonProducto = new javax.swing.JButton();
        jButtonCociente = new javax.swing.JButton();
        jButtonNueve = new javax.swing.JButton();
        jButtonOcho = new javax.swing.JButton();
        jButtonPotencia = new javax.swing.JButton();
        jButtonAllClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora M. Zapata & M. Verduzco");
        setBackground(new java.awt.Color(0, 0, 0));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setText("Welcome");

        jButtonCero.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCero.setText("0");
        jButtonCero.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonCero.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonCero.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCeroActionPerformed(evt);
            }
        });

        jButtonPunto.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPunto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonPunto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPunto.setText(".");
        jButtonPunto.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonPunto.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonPunto.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuntoActionPerformed(evt);
            }
        });

        jButtonAbierto.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAbierto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAbierto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAbierto.setText("(");
        jButtonAbierto.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonAbierto.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonAbierto.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonAbierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbiertoActionPerformed(evt);
            }
        });

        jButtonCerrado.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCerrado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCerrado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrado.setText(")");
        jButtonCerrado.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonCerrado.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonCerrado.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonCerrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerradoActionPerformed(evt);
            }
        });

        jButtonIgual.setBackground(new java.awt.Color(255, 0, 0));
        jButtonIgual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonIgual.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIgual.setText("=");
        jButtonIgual.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonIgual.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonIgual.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jButtonUno.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonUno.setText("1");
        jButtonUno.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonUno.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonUno.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnoActionPerformed(evt);
            }
        });

        jButtonDos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDos.setText("2");
        jButtonDos.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonDos.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonDos.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDosActionPerformed(evt);
            }
        });

        jButtonTres.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTres.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonTres.setText("3");
        jButtonTres.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonTres.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonTres.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTresActionPerformed(evt);
            }
        });

        jButtonMas.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMas.setText("+");
        jButtonMas.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonMas.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonMas.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });

        jButtonMenos.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMenos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMenos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMenos.setText("-");
        jButtonMenos.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonMenos.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonMenos.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jButtonCuatro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuatro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCuatro.setText("4");
        jButtonCuatro.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonCuatro.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonCuatro.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuatroActionPerformed(evt);
            }
        });

        jButtonCinco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCinco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCinco.setText("5");
        jButtonCinco.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonCinco.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonCinco.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCincoActionPerformed(evt);
            }
        });

        jButtonSeis.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSeis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSeis.setText("6");
        jButtonSeis.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonSeis.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonSeis.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeisActionPerformed(evt);
            }
        });

        jButtonSiete.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSiete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSiete.setText("7");
        jButtonSiete.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonSiete.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonSiete.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSieteActionPerformed(evt);
            }
        });

        jButtonProducto.setBackground(new java.awt.Color(0, 0, 0));
        jButtonProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonProducto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProducto.setText("x");
        jButtonProducto.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonProducto.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonProducto.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductoActionPerformed(evt);
            }
        });

        jButtonCociente.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCociente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCociente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCociente.setText("÷");
        jButtonCociente.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonCociente.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonCociente.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonCociente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCocienteActionPerformed(evt);
            }
        });

        jButtonNueve.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNueve.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonNueve.setText("9");
        jButtonNueve.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonNueve.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonNueve.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNueveActionPerformed(evt);
            }
        });

        jButtonOcho.setBackground(new java.awt.Color(255, 255, 255));
        jButtonOcho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonOcho.setText("8");
        jButtonOcho.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonOcho.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonOcho.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOchoActionPerformed(evt);
            }
        });

        jButtonPotencia.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPotencia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonPotencia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPotencia.setText("^");
        jButtonPotencia.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonPotencia.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonPotencia.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotenciaActionPerformed(evt);
            }
        });

        jButtonAllClear.setBackground(new java.awt.Color(0, 0, 255));
        jButtonAllClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAllClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAllClear.setText("AC");
        jButtonAllClear.setMaximumSize(new java.awt.Dimension(70, 50));
        jButtonAllClear.setMinimumSize(new java.awt.Dimension(70, 50));
        jButtonAllClear.setPreferredSize(new java.awt.Dimension(70, 50));
        jButtonAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonUno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCuatro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSiete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonAbierto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCerrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonMenos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCociente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonNueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAllClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCociente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCerrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAbierto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCeroActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="0"); // se concatena el simbolo del dígito a la cadena y los demás botones son análogos.
    }//GEN-LAST:event_jButtonCeroActionPerformed

    private void jButtonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSieteActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="7");
    }//GEN-LAST:event_jButtonSieteActionPerformed

    private void jButtonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="*");
    }//GEN-LAST:event_jButtonProductoActionPerformed

    private void jButtonCocienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCocienteActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="/");
    }//GEN-LAST:event_jButtonCocienteActionPerformed

    private void jButtonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNueveActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="9");
    }//GEN-LAST:event_jButtonNueveActionPerformed

    private void jButtonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOchoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="8");
    }//GEN-LAST:event_jButtonOchoActionPerformed

    private void jButtonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotenciaActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="^");
    }//GEN-LAST:event_jButtonPotenciaActionPerformed

    private void jButtonAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllClearActionPerformed
        // TODO add your handling code here:
        cad=""; // se limpia la cadena
        jTextField1.setText(cad);
    }//GEN-LAST:event_jButtonAllClearActionPerformed

    private void jButtonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeisActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="6");
    }//GEN-LAST:event_jButtonSeisActionPerformed

    private void jButtonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCincoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="5");
    }//GEN-LAST:event_jButtonCincoActionPerformed

    private void jButtonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuatroActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="4");
    }//GEN-LAST:event_jButtonCuatroActionPerformed

    private void jButtonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="1");
    }//GEN-LAST:event_jButtonUnoActionPerformed

    private void jButtonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDosActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="2");
    }//GEN-LAST:event_jButtonDosActionPerformed

    private void jButtonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTresActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="3");
    }//GEN-LAST:event_jButtonTresActionPerformed

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="+");
    }//GEN-LAST:event_jButtonMasActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="-");
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuntoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+=".");
    }//GEN-LAST:event_jButtonPuntoActionPerformed

    private void jButtonAbiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbiertoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+="(");
    }//GEN-LAST:event_jButtonAbiertoActionPerformed

    private void jButtonCerradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerradoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(cad+=")");
    }//GEN-LAST:event_jButtonCerradoActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        // TODO add your handling code here:
        cad=Funciones.evaluacionFinal(cad); // se ejecuta la función y se guarda el valor
        jTextField1.setText(cad); // se imprime el valor
    }//GEN-LAST:event_jButtonIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbierto;
    private javax.swing.JButton jButtonAllClear;
    private javax.swing.JButton jButtonCero;
    private javax.swing.JButton jButtonCerrado;
    private javax.swing.JButton jButtonCinco;
    private javax.swing.JButton jButtonCociente;
    private javax.swing.JButton jButtonCuatro;
    private javax.swing.JButton jButtonDos;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonNueve;
    private javax.swing.JButton jButtonOcho;
    private javax.swing.JButton jButtonPotencia;
    private javax.swing.JButton jButtonProducto;
    private javax.swing.JButton jButtonPunto;
    private javax.swing.JButton jButtonSeis;
    private javax.swing.JButton jButtonSiete;
    private javax.swing.JButton jButtonTres;
    private javax.swing.JButton jButtonUno;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
